### ISSUE TITLE
ext ex

### ISSUE THREAD

**Issue by benpriestman** [azimux/externals#9]
1 issue, 1 feature request:

I'm having trouble making ext ex work.

From my understanding, ext ex should allow me to export the sub-projects with out the main project.

When I run:
targetdir>ext --workdir /path/to/full/ext/checkout ex
as in the tutorial, I get:
/usr/lib/ruby/1.8/fileutils.rb:264:in `rmdir': Directory not empty - modules/apache (Errno::ENOTEMPTY)
        from /usr/lib/ruby/1.8/fileutils.rb:264:in`rmdir'
        from /usr/lib/ruby/1.8/fileutils.rb:263:in `each'
        from /usr/lib/ruby/1.8/fileutils.rb:263:in`rmdir'
        from /usr/lib/ruby/gems/1.8/gems/ext-1.1.0/bin/../lib/externals/extensions/file_utils.rb:21:in `rmdir_ie'
        from /usr/lib/ruby/gems/1.8/gems/ext-1.1.0/bin/../lib/externals/scms/svn_project.rb:12:in`co'
        from /usr/lib/ruby/gems/1.8/gems/ext-1.1.0/bin/../lib/externals/ext.rb:371:in `send'
        from /usr/lib/ruby/gems/1.8/gems/ext-1.1.0/bin/../lib/externals/ext.rb:371:in`co'
        from /usr/lib/ruby/gems/1.8/gems/ext-1.1.0/bin/../lib/externals/ext.rb:371:in `each'
        from /usr/lib/ruby/gems/1.8/gems/ext-1.1.0/bin/../lib/externals/ext.rb:371:in`co'
        from /usr/lib/ruby/gems/1.8/gems/ext-1.1.0/bin/../lib/externals/ext.rb:212:in `send'
        from /usr/lib/ruby/gems/1.8/gems/ext-1.1.0/bin/../lib/externals/ext.rb:212:in`run'
        from /usr/lib/ruby/gems/1.8/gems/ext-1.1.0/bin/../lib/externals/ext.rb:211:in `chdir'
        from /usr/lib/ruby/gems/1.8/gems/ext-1.1.0/bin/../lib/externals/ext.rb:211:in`run'
        from /usr/lib/ruby/gems/1.8/gems/ext-1.1.0/bin/ext:6
        from /usr/bin/ext:19:in `load'
        from /usr/bin/ext:19

This is using ruby 1.8 on rhel 6.

module/apache is the first project in by externals puppet repository.

The feature request is to be able to export just one sub-project:

> ext --workdir /path/to/workdir ex projectname

Lastly, would you prefer issues, requests to be added here, on lighthouse, or on ruby forge?

**Comment by azimux** [comment]
Hey hey! This is soooooo old I'm not sure if there's anything left to do here. Looks like an improved error message is one thing that could have helped. Also though seems like there's a request for exporting a specific subproject to a specific place?

I'll close this assuming you've moved way beyond this ages ago but if you or anybody else desires such a feature please reopen an issue specific to it

Thanks!!

Cheers from across the decade!
